import os
import tempfile
import uuid
from fastapi import APIRouter, UploadFile, File, HTTPException
from services.analysis_service import run_analysis

router = APIRouter()

ALLOWED_EXTENSIONS = {".pdf", ".docx", ".doc"}

@router.post("/upload")
async def upload_document(file: UploadFile = File(...)):
    """
    Core File Ingestion Pathway. 
    Streams dynamic `multipart/form-data` natively converting async files to temporary disk structures,
    passing parsing pathways into local AI sub-modules.
    """
    if not file.filename:
        raise HTTPException(status_code=400, detail="Empty filename provided.")

    ext = os.path.splitext(file.filename)[1].lower()
    if ext not in ALLOWED_EXTENSIONS:
        raise HTTPException(status_code=400, detail=f"File extension {ext} not supported. Use .pdf or .docx")

    # Ingesting file byte payload explicitly
    content = await file.read()
    if not content:
        raise HTTPException(status_code=400, detail="Empty file payload submitted.")

    # We must construct a native persistent temporary file to bridge FastAPI upload schemas -> python local extraction systems safely.
    temp_dir = tempfile.gettempdir()
    safe_name = f"{uuid.uuid4().hex}{ext}"
    temp_path = os.path.join(temp_dir, safe_name)

    try:
        with open(temp_path, "wb") as f:
            f.write(content)

        # Triggers Model Bridge natively!
        analysis_data = await run_analysis(temp_path)
        
        # Validates potential local errors internally generated by the structural schema intelligently
        if "error" in analysis_data:
            raise HTTPException(status_code=500, detail=analysis_data["error"])
            
        return analysis_data

    except HTTPException:
        # Allow internal validation checks to bubble cleanly
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Processing pipeline failed: {str(e)}")
        
    finally:
        # Perform dynamic garbage collection, deleting temporary file out of the OS securely.
        if os.path.exists(temp_path):
            try:
                os.remove(temp_path)
            except:
                pass
